from typing import Optional, Union, Type, Dict
from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator
from gameboy_worlds.emulation.harvest_moon.parsers import (
    HarvestMoon1Parser,
    HarvestMoon2Parser,
    HarvestMoon3Parser,
)
from gameboy_worlds.emulation.harvest_moon.trackers import (
    HarvestMoonOCRTracker,
    HarvestMoonCowBarnTracker,   
    HarvestMoonChickenCoopTracker,
    HarvestMoonStorageTracker,
    HarvestMoonPickupWaterCanTracker,
    HarvestMoonPickupCowBellTracker,
    HarvestMoonGoToSleepTracker,
    HarvestMoonFeedSpiritTracker,
    HarvestMoonHelpSpiritEarthquakeTracker,
    HarvestMoonWaterTurnipTracker,
    HarvestMoonBuyMaterialTracker,
    HarvestMoonBuyChickenTracker,
    HarvestMoonBuyCowTracker,
    HarvestMoonSellChickenTracker,
    HarvestMoonBuyCowBrushTracker,
    HarvestMoonBuySaddlebagTracker,
    HarvestMoonBuyMilkerTracker,
    HarvestMoonBuyRiceBallTracker,
    HarvestMoonOpenMenuTracker,
    HarvestMoonOpenStorageListTracker,
    HarvestMoonFindRainyMoneyTracker,
    HarvestMoonFindLostBirdTracker,
    HarvestMoonSpeakToBlueHairGirlTracker,
    HarvestMoonFillChickenFodderTracker,
    HarvestMoonPickupSickleTracker,
    HarvestMoonPickupHoeTracker,
    HarvestMoonPickupHammerTracker,
    HarvestMoonPickupGrassSeedTracker,
    HarvestMoonBuyCroissantTracker,
    HarvestMoonBuyCakeTracker,
    HarvestMoonBuyGrapeJuiceTracker,
    HarvestMoonGoToChurchPrayTracker,
    HarvestMoonSpeakToGoldenHairGirlTracker,
    HarvestMoonSpeakToPinkHairGirlTracker,
    HarvestMoon1SpeakToBlueHairGirlWGTracker,
    HarvestMoon1SpeakToPinkHairGirlWGTracker,
    HarvestMoon1SpeakToRedHairGirlWGTracker,
    HarvestMoon1RestoreFenceTracker,

    # HM2
    HarvestMoon2CowBarnTracker,
    HarvestMoon2ChickenCoopTracker,
    HarvestMoon2FindLuckyMoneyTracker,
    HarvestMoon2HospitalEntranceTracker,
    HarvestMoon2ToolShopEntranceTracker,
    HarvestMoon2CarpenterEntranceTracker,
    HarvestMoon2AnimalShopEntranceTracker,
    HarvestMoon2LibraryEntranceTracker,
    HarvestMoon2FlowerShopEntranceTracker,
    HarvestMoon2GetBridgeEstimateTracker,
    HarvestMoon2BuyMilkerTracker,
    
    HarvestMoonReadVillageSignTracker,
    HarvestMoonReadFarmSignTracker,
    HarvestMoon2ReadSecretGardenSignTracker,
    
    # HM3
    HarvestMoon3RemoveWeedTracker,
    HarvestMoon3PickUpCherryTracker,
    HarvestMoon3WaterCenterWatermelonTracker,
    HarvestMoon3HatchEggTracker,
    HarvestMoon3FillChickenFodderTracker,
    HarvestMoon3BuyFodderSetTracker,
    HarvestMoon3BuyHorseMedicineTracker,
    HarvestMoon3SpeakToKateTracker,
    HarvestMoon3BreakRockTracker,
    HarvestMoon3WaterCenterSPotatoTracker,
    HarvestMoon3HarvestTargetPotatoTracker,
    HarvestMoon3ReadAnimalCh2Tracker,
    HarvestMoon3HarvestCenterTurnipTracker,
    HarvestMoon3SellChickenTracker,
    HarvestMoon3PickBerryTracker,
    HarvestMoon3CheckPlayerMoneyTracker,
    HarvestMoon3HarvestCenterEggplantTopTracker,
    HarvestMoon3ChickenCoopTracker,
    HarvestMoon3ReadSecretGardenSignTracker,
    HarvestMoon3ReadFerrySignTracker,
    HarvestMoon3FindSecretSavingsTracker,
    HarvestMoon3ChooseTeaTracker,
    HarvestMoon3ChooseAsparagusSeedsTracker,
    HarvestMoon3BuyPotatoSeedsTracker,
    HarvestMoon3BuyTurnipSeedsTracker,
    HarvestMoon3ReadMorningMarketSignTracker,
    HarvestMoon3ReadStorageSignTracker,
    HarvestMoon3SpeakToKirkVillageTracker,
    HarvestMoon3TakeFerryTracker,
    HarvestMoon3SpeakToJoeTracker,
    HarvestMoon3SpeakToLukiaTracker,
    HarvestMoon3SpeakToLucusTracker,
    HarvestMoon3SpeakToLylaTracker,
    HarvestMoon3BuyHorseSaddleTracker,
    HarvestMoon3BuyFlowerVaseTracker,
    HarvestMoon3BuyMealSetTracker,
    HarvestMoon3BuyCoffeeTracker,
    HarvestMoon3FeedCowFodderTracker,
    HarvestMoon3FarmEntranceTracker,
    HarvestMoon3VillageEntranceTracker,
    HarvestMoon3GrasslandEntranceTracker,
    HarvestMoon3ForestEntranceTracker,
    HarvestMoon3CliffEntranceTracker,
    HarvestMoon3MountainEntranceTracker,
    HarvestMoon3ShoppingMallEntranceTracker,
    HarvestMoon3ShoppingMallSecondFloorTracker,
    HarvestMoon3FarmersUnionEntranceTracker,
    HarvestMoon3AquariumEntranceTracker,
    HarvestMoon3TheatreEntranceTracker,
    HarvestMoon3HotSpringEntranceTracker,
    HarvestMoon2ReadCropFieldSignTracker,
    HarvestMoonReadNoticeBoardTracker,
    HarvestMoon2RestaurantEntranceTracker,
    HarvestMoon2BuyLunchSetTracker,
    HarvestMoon2BuyBeverageSetTracker,
    HarvestMoon2BuyTodaysSpecialTracker,
    HarvestMoon2GoToBedTracker,
    HarvestMoon2EquipSickleTracker,
    HarvestMoon2EquipHammerTracker,
    HarvestMoon2EquipFishingRodTracker,
    HarvestMoon2EquipNetReplacingAxTracker,
    HarvestMoon2EquipRosemarySeedsReplacingAxTracker,
    HarvestMoon2EquipSickleReplacingSprinklerTracker,
    HarvestMoon2EquipNetReplacingHoeTracker,
    HarvestMoon1HatchEggTracker,
    HarvestMoon1BreakRockTracker,
    HarvestMoon1BreakRightmostRockTracker,
    HarvestMoon1RemoveLowestWeedTracker,
    HarvestMoon1CutLowestWeedTracker,
    HarvestMoon1RemoveTopLeftWeedTracker,
    HarvestMoon1CutTopLeftWeedTracker,
    HarvestMoon1HarvestCenterGrasslineTracker,
    # HarvestMoon1RestoreFenceTracker,
    HarvestMoon1HarvestCenterTurnipTracker,
    HarvestMoon1WaterCenterTurnipTracker,
    HarvestMoon1WaterCenterPotatoTracker,
    HarvestMoon1HarvestCenterPotatoTracker,
    HarvestMoon1GetHomeExpansionEstimateTracker,
    HarvestMoon1FillCowFodderTracker,
    # HarvestMoon2ShipEggplantTracker,
    HarvestMoon2Cross500mLineTracker,
    HarvestMoon2Cross1000mLineTracker,
    HarvestMoon2HarvestCenterEggplantTracker,
    HarvestMoon2HarvestCenterCarrotTracker,
    HarvestMoon2WaterCenterPotatoTracker,
    HarvestMoon2WaterCenterAsparagusTracker,
    HarvestMoon2ReadComputersArticleTracker,
    HarvestMoon2ReadBouldersArticleTracker,
    HarvestMoon2ReadCropsArticleTracker,
    HarvestMoon2RemoveLeftmostWeedTracker,
    HarvestMoon2PickBerryTracker,
    HarvestMoon2PickBerryAboveTracker,
    HarvestMoon2SpeakToBlueHairGirlTracker,
    HarvestMoon2SpeakToPurpleHairGirlTracker,
    HarvestMoon2SpeakToBlondeGirlTracker,
    HarvestMoon2HatchEggTracker,
    HarvestMoon2BuyCowTracker,
    HarvestMoon2SellCowTracker,
    HarvestMoon2SellChickenTracker,
    HarvestMoon2GetHothouseEstimateTracker,
    HarvestMoon2BuyChickenTracker,
    HarvestMoon2FillChickenFodderTracker,
    HarvestMoon2WaterCornFieldTracker,
    HarvestMoon2CutCenterCornTracker,
    HarvestMoon2WaterCabbageFieldTracker,
)

GAME_TO_GB_NAME = {
    "harvest_moon_1": "HarvestMoon1.gbc",
    "harvest_moon_2": "HarvestMoon2.gbc",
    "harvest_moon_3": "HarvestMoon3.gbc",
}
""" Expected save name for each game. Save the file to <storage_dir_from_config_file>/<game_name>_rom_data/<gb_name>"""

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "harvest_moon_1": HarvestMoon1Parser,
    "harvest_moon_2": HarvestMoon2Parser,
    "harvest_moon_3": HarvestMoon3Parser,
}
""" Mapping of game names to their corresponding strongest StateParser classes. 
Unless you have a very good reason, you should always use the STRONGEST possible parser for a given game. 
The parser itself does not affect performance, as for it to perform a read / screen comparison operation , it must be called upon by the state tracker.
This means there is never a reason to use a weaker parser. 
"""


AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "harvest_moon_1": {
        "default": HarvestMoonOCRTracker,
        "cow_barn_test": HarvestMoonCowBarnTracker,
        "chicken_coop_test": HarvestMoonChickenCoopTracker,
        "storage_shed_test": HarvestMoonStorageTracker,
        "pickup_watercan_test": HarvestMoonPickupWaterCanTracker,
        "pickup_cowbell_test": HarvestMoonPickupCowBellTracker,
        "go_to_sleep_test": HarvestMoonGoToSleepTracker,
        "feed_spirit_test": HarvestMoonFeedSpiritTracker,
        "help_spirit_earthquake_test": HarvestMoonHelpSpiritEarthquakeTracker,
        "water_turnip_test": HarvestMoonWaterTurnipTracker,
        "buy_material_test": HarvestMoonBuyMaterialTracker,
        "buy_chicken_test": HarvestMoonBuyChickenTracker,
        "buy_cow_test": HarvestMoonBuyCowTracker,
        "sell_chicken_test": HarvestMoonSellChickenTracker,
        "buy_cow_brush_test": HarvestMoonBuyCowBrushTracker,
        "buy_saddlebag_test": HarvestMoonBuySaddlebagTracker,
        "buy_milker_test": HarvestMoonBuyMilkerTracker,
        "buy_rice_ball_test": HarvestMoonBuyRiceBallTracker,
        "open_storage_list_test": HarvestMoonOpenStorageListTracker,
        "find_rainy_money_test": HarvestMoonFindRainyMoneyTracker,
        "find_lost_bird_test": HarvestMoonFindLostBirdTracker,
        "speak_to_blue_hair_girl_test": HarvestMoonSpeakToBlueHairGirlTracker,
        "fill_chicken_fodder_test": HarvestMoonFillChickenFodderTracker,
        "pickup_sickle_test": HarvestMoonPickupSickleTracker,
        "pickup_hoe_test": HarvestMoonPickupHoeTracker,
        "pickup_hammer_test": HarvestMoonPickupHammerTracker,
        "pickup_grass_seed_test": HarvestMoonPickupGrassSeedTracker,
        "buy_croissant_test": HarvestMoonBuyCroissantTracker,
        "buy_cake_test": HarvestMoonBuyCakeTracker,
        "buy_grape_juice_test": HarvestMoonBuyGrapeJuiceTracker,
        "go_to_church_pray_test": HarvestMoonGoToChurchPrayTracker,
        "speak_to_golden_hair_girl_test": HarvestMoonSpeakToGoldenHairGirlTracker,
        "speak_to_pink_hair_girl_test": HarvestMoonSpeakToPinkHairGirlTracker,
        "speak_to_blue_hair_girl_wg_test": HarvestMoon1SpeakToBlueHairGirlWGTracker,
        "speak_to_pink_hair_girl_wg_test": HarvestMoon1SpeakToPinkHairGirlWGTracker,
        "speak_to_red_hair_girl_wg_test": HarvestMoon1SpeakToRedHairGirlWGTracker,
        "open_menu_test": HarvestMoonOpenMenuTracker,
        "hatch_egg_test": HarvestMoon1HatchEggTracker,
        "break_rock_test": HarvestMoon1BreakRockTracker,
        "break_rightmost_rock_test": HarvestMoon1BreakRightmostRockTracker,
        "remove_lowest_weed_test": HarvestMoon1RemoveLowestWeedTracker,
        "cut_lowest_weed_test": HarvestMoon1CutLowestWeedTracker,
        "remove_top_left_weed_test": HarvestMoon1RemoveTopLeftWeedTracker,
        "cut_top_left_weed_test": HarvestMoon1CutTopLeftWeedTracker,
        "harvest_center_grassline_test": HarvestMoon1HarvestCenterGrasslineTracker,
        "restore_fence_test": HarvestMoon1RestoreFenceTracker,
        "harvest_center_turnip_test": HarvestMoon1HarvestCenterTurnipTracker,
        "water_center_turnip_test": HarvestMoon1WaterCenterTurnipTracker,
        "water_center_potato_test": HarvestMoon1WaterCenterPotatoTracker,
        "harvest_center_potato_test": HarvestMoon1HarvestCenterPotatoTracker,
        "get_home_expansion_estimate_test": HarvestMoon1GetHomeExpansionEstimateTracker,
        "fill_cow_fodder_test": HarvestMoon1FillCowFodderTracker,
    },
    "harvest_moon_2": {
        "default": HarvestMoonOCRTracker,
        "cow_barn_test": HarvestMoon2CowBarnTracker,
        "chicken_coop_test": HarvestMoon2ChickenCoopTracker,
        "hospital_entrance_test": HarvestMoon2HospitalEntranceTracker,
        "animal_shop_entrance_test": HarvestMoon2AnimalShopEntranceTracker,
        "library_entrance_test": HarvestMoon2LibraryEntranceTracker,
        "tool_shop_entrance_test": HarvestMoon2ToolShopEntranceTracker,
        "carpenter_entrance_test": HarvestMoon2CarpenterEntranceTracker,
        "find_lucky_money_test": HarvestMoon2FindLuckyMoneyTracker,        
        "flower_shop_entrance_test": HarvestMoon2FlowerShopEntranceTracker,
        "get_bridge_estimate_test": HarvestMoon2GetBridgeEstimateTracker,
        "buy_milker_test": HarvestMoon2BuyMilkerTracker,
        "restaurant_entrance_test": HarvestMoon2RestaurantEntranceTracker,
        "buy_lunch_set_test": HarvestMoon2BuyLunchSetTracker,
        "buy_beverage_set_test": HarvestMoon2BuyBeverageSetTracker,
        "buy_todays_special_test": HarvestMoon2BuyTodaysSpecialTracker,
        "go_to_bed_test": HarvestMoon2GoToBedTracker,
        "read_secret_garden_sign_test": HarvestMoon2ReadSecretGardenSignTracker,
        "read_crop_field_sign_test": HarvestMoon2ReadCropFieldSignTracker,
        "equip_sickle_test": HarvestMoon2EquipSickleTracker,
        "equip_hammer_test": HarvestMoon2EquipHammerTracker,
        "equip_fishing_rod_test": HarvestMoon2EquipFishingRodTracker,
        "equip_net_replacing_ax_test": HarvestMoon2EquipNetReplacingAxTracker,
        "equip_rosemary_seeds_replacing_ax_test": HarvestMoon2EquipRosemarySeedsReplacingAxTracker,
        "equip_sickle_replacing_sprinkler_test": HarvestMoon2EquipSickleReplacingSprinklerTracker,
        "equip_net_replacing_hoe_test": HarvestMoon2EquipNetReplacingHoeTracker,
        "cross_500m_line_test": HarvestMoon2Cross500mLineTracker,
        "cross_1000m_line_test": HarvestMoon2Cross1000mLineTracker,
        "harvest_center_eggplant_test": HarvestMoon2HarvestCenterEggplantTracker,
        "harvest_center_carrot_test": HarvestMoon2HarvestCenterCarrotTracker,
        "water_center_potato_test": HarvestMoon2WaterCenterPotatoTracker,
        "water_center_asparagus_test": HarvestMoon2WaterCenterAsparagusTracker,
        "read_computers_article_test": HarvestMoon2ReadComputersArticleTracker,
        "read_boulders_article_test": HarvestMoon2ReadBouldersArticleTracker,
        "read_selling_crops_article_test": HarvestMoon2ReadCropsArticleTracker,
        "remove_leftmost_weed_test": HarvestMoon2RemoveLeftmostWeedTracker,
        "pick_berry_test": HarvestMoon2PickBerryTracker,
        "pick_berry_above_test": HarvestMoon2PickBerryAboveTracker,
        "speak_to_blue_hair_girl_test": HarvestMoon2SpeakToBlueHairGirlTracker,
        "speak_to_purple_hair_girl_test": HarvestMoon2SpeakToPurpleHairGirlTracker,
        "speak_to_blonde_girl_test": HarvestMoon2SpeakToBlondeGirlTracker,
        "hatch_egg_test": HarvestMoon2HatchEggTracker,
        "buy_cow_test": HarvestMoon2BuyCowTracker,
        "sell_cow_test": HarvestMoon2SellCowTracker,
        "sell_chicken_test": HarvestMoon2SellChickenTracker,
        "get_hothouse_estimate_test": HarvestMoon2GetHothouseEstimateTracker,
        "buy_chicken_test": HarvestMoon2BuyChickenTracker,
        "fill_chicken_fodder_test": HarvestMoon2FillChickenFodderTracker,
        "water_corn_field_test": HarvestMoon2WaterCornFieldTracker,
        "cut_center_corn_test": HarvestMoon2CutCenterCornTracker,
        "water_cabbage_field_test": HarvestMoon2WaterCabbageFieldTracker,
        
        "storage_shed_test": HarvestMoonStorageTracker,
        "water_turnip_test": HarvestMoonWaterTurnipTracker,
        "open_storage_list_test": HarvestMoonOpenStorageListTracker,
        "read_village_sign_test": HarvestMoonReadVillageSignTracker,
        "read_farm_sign_test": HarvestMoonReadFarmSignTracker,
        "read_notice_board_test": HarvestMoonReadNoticeBoardTracker,
        "open_menu_test": HarvestMoonOpenMenuTracker,
    },
    "harvest_moon_3": {
        "default": HarvestMoonOCRTracker,
        "chicken_coop_test": HarvestMoon3ChickenCoopTracker,
        "read_secret_garden_sign_test": HarvestMoon3ReadSecretGardenSignTracker,
        "read_morning_market_sign_test": HarvestMoon3ReadMorningMarketSignTracker,
        "read_storage_sign_test": HarvestMoon3ReadStorageSignTracker,
        "speak_to_Kirk_village_test": HarvestMoon3SpeakToKirkVillageTracker,
        "take_ferry_back_test": HarvestMoon3TakeFerryTracker,
        "speak_to_Joe_test": HarvestMoon3SpeakToJoeTracker,
        "speak_to_Lukia_test": HarvestMoon3SpeakToLukiaTracker,
        "speak_to_Lucus_test": HarvestMoon3SpeakToLucusTracker,
        "speak_to_Lyla_test": HarvestMoon3SpeakToLylaTracker,
        "buy_horse_saddle_test": HarvestMoon3BuyHorseSaddleTracker,
        "buy_flower_vase_test": HarvestMoon3BuyFlowerVaseTracker,
        "buy_meal_set_test": HarvestMoon3BuyMealSetTracker,
        "choose_coffee_to_buy_test": HarvestMoon3BuyCoffeeTracker,
        "shopping_mall_entrance_test": HarvestMoon3ShoppingMallEntranceTracker,
        "shopping_mall_second_floor_test": HarvestMoon3ShoppingMallSecondFloorTracker,
        "farmers_union_entrance_test": HarvestMoon3FarmersUnionEntranceTracker,
        "aquarium_entrance_test": HarvestMoon3AquariumEntranceTracker,
        "theatre_entrance_test": HarvestMoon3TheatreEntranceTracker,
        "hot_spring_entrance_test": HarvestMoon3HotSpringEntranceTracker,
        "open_menu_test": HarvestMoonOpenMenuTracker,
        "farm_entrance_test": HarvestMoon3FarmEntranceTracker,
        "village_entrance_test": HarvestMoon3VillageEntranceTracker,
        "grassland_entrance_test": HarvestMoon3GrasslandEntranceTracker, 
        "forest_entrance_test": HarvestMoon3ForestEntranceTracker,
        "cliff_entrance_test": HarvestMoon3CliffEntranceTracker,
        "mountain_entrance_test": HarvestMoon3MountainEntranceTracker,
        "read_ferry_sign_test": HarvestMoon3ReadFerrySignTracker,
        "find_secret_savings_test": HarvestMoon3FindSecretSavingsTracker,
        "choose_tea_to_buy_test": HarvestMoon3ChooseTeaTracker,
        "choose_asparagus_seeds_to_buy_test": HarvestMoon3ChooseAsparagusSeedsTracker,
        "choose_potato_seeds_to_buy_test": HarvestMoon3BuyPotatoSeedsTracker,
        "choose_turnip_seeds_to_buy_test": HarvestMoon3BuyTurnipSeedsTracker,
        "fill_cow_fodder_test": HarvestMoon3FeedCowFodderTracker,
        "break_rock_test": HarvestMoon3BreakRockTracker,
        "remove_weed_test": HarvestMoon3RemoveWeedTracker,
        "pick_up_cherry_test": HarvestMoon3PickUpCherryTracker,
        "water_center_watermelon_test": HarvestMoon3WaterCenterWatermelonTracker,
        "hatch_egg_test": HarvestMoon3HatchEggTracker,
        "fill_chicken_fodder_test": HarvestMoon3FillChickenFodderTracker,
        "buy_fodder_set_test": HarvestMoon3BuyFodderSetTracker,
        "buy_horse_medicine_test": HarvestMoon3BuyHorseMedicineTracker,
        "speak_to_kate_test": HarvestMoon3SpeakToKateTracker,
        "water_center_spotato_test": HarvestMoon3WaterCenterSPotatoTracker,
        "harvest_target_potato_test": HarvestMoon3HarvestTargetPotatoTracker,
        "read_animal_ch2_test": HarvestMoon3ReadAnimalCh2Tracker,
        "harvest_center_turnip_test": HarvestMoon3HarvestCenterTurnipTracker,
        "sell_chicken_test": HarvestMoon3SellChickenTracker,
        "pick_up_berry_test": HarvestMoon3PickBerryTracker,
        "check_player_money_test": HarvestMoon3CheckPlayerMoneyTracker,
        "harvest_center_eggplant_test": HarvestMoon3HarvestCenterEggplantTopTracker,

    },
}
""" Mapping of game names to their available StateTracker classes with string identifiers. """


AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "harvest_moon_1": {"default": Emulator},
    "harvest_moon_2": {"default": Emulator},
    "harvest_moon_3": {"default": Emulator},
}
""" Mapping of game names to their available Emulator classes with string identifiers. """
