from typing import Optional, Union, Type, Dict
from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator
from gameboy_worlds.emulation.harvest_moon.parsers import (
    HarvestMoon1Parser,
    HarvestMoon2Parser,
    HarvestMoon3Parser,
)
from gameboy_worlds.emulation.harvest_moon.trackers import (
    HarvestMoonOCRTracker,
    HarvestMoonCowBarnTracker,   
    HarvestMoonChickenCoopTracker,
    HarvestMoonStorageTracker,
    HarvestMoonPickupWaterCanTracker,
    HarvestMoonGoToSleepTracker,
    HarvestMoonFeedSpiritTracker,
    HarvestMoonHelpSpiritEarthquakeTracker,
    HarvestMoonWaterTurnipTracker,
    HarvestMoonBuyMaterialTracker,
    HarvestMoonBuyChickenTracker,
    HarvestMoonBuyCowBrushTracker,
    HarvestMoonBuySaddlebagTracker,
    HarvestMoonBuyMilkerTracker,
    HarvestMoonBuyPotatoSeedsTracker,
    HarvestMoonBuyTurnipSeedsTracker,
    HarvestMoonBuyRiceBallTracker,
    HarvestMoonOpenMenuTracker,
    HarvestMoonOpenStorageListTracker,
    HarvestMoonFindRainyMoneyTracker,
    HarvestMoonFindLostBirdTracker,
    HarvestMoonSpeakToBlueHairGirlTracker,
    HarvestMoonFillChickenFodderTracker,
    HarvestMoonPickupSickleTracker,
    HarvestMoonPickupHoeTracker,
    HarvestMoonPickupHammerTracker,
    HarvestMoonPickupGrassSeedTracker,
    HarvestMoonBuyCroissantTracker,
    HarvestMoonBuyCakeTracker,
    HarvestMoonGoToChurchPrayTracker,
    HarvestMoonSpeakToGoldenHairGirlTracker,
    HarvestMoonSpeakToPinkHairGirlTracker,
    
    # HM2
    HarvestMoon2CowBarnTracker,
    HarvestMoon2ChickenCoopTracker,
    HarvestMoon2FindLuckyMoneyTracker,
    HarvestMoon2HospitalEntranceTracker,
    HarvestMoon2ToolShopEntranceTracker,
    HarvestMoon2CarpenterEntranceTracker,
    HarvestMoon2AnimalShopEntranceTracker,
    HarvestMoon2LibraryEntranceTracker,
    HarvestMoon2FlowerShopEntranceTracker,
    HarvestMoon2BuyPotatoSeedsTracker,
    HarvestMoon2BuyAsparagusSeedsTracker,
    
    HarvestMoonReadVillageSignTracker,
    HarvestMoonReadFarmSignTracker,
    HarvestMoon2ReadSecretGardenSignTracker,
    
    # HM3
    HarvestMoon3ChickenCoopTracker,
    HarvestMoon3ReadSecretGardenSignTracker,
    HarvestMoon3ReadFerrySignTracker,
    HarvestMoon3FindSecretSavingsTracker,
    HarvestMoon3ChooseTeaTracker,
    HarvestMoon3ChooseAsparagusSeedsTracker,
    HarvestMoon3BuyPotatoSeedsTracker,
    HarvestMoon3BuyTurnipSeedsTracker,
    HarvestMoon3ReadMorningMarketSignTracker,
    HarvestMoon3ReadStorageSignTracker,
    HarvestMoon3SpeakToKirkVillageTracker,
    HarvestMoon3TakeFerryTracker,
    HarvestMoon3SpeakToJoeTracker,
    HarvestMoon3SpeakToLukiaTracker,
    HarvestMoon3SpeakToLucusTracker,
    HarvestMoon3SpeakToLylaTracker,
    HarvestMoon3BuyMealSetTracker,
    HarvestMoon3BuyCoffeeTracker,
    HarvestMoon3FeedCowFodderTracker,
    HarvestMoon3FarmEntranceTracker,
    HarvestMoon3VillageEntranceTracker,
    HarvestMoon3GrasslandEntranceTracker,
    HarvestMoon3ForestEntranceTracker,
    HarvestMoon3CliffEntranceTracker,
    HarvestMoon3MountainEntranceTracker,
    HarvestMoon3ShoppingMallEntranceTracker,
    HarvestMoon3FarmersUnionEntranceTracker,
    HarvestMoon3AquariumEntranceTracker,
    HarvestMoon3TheatreEntranceTracker,
    HarvestMoon3HotSpringEntranceTracker,
    HarvestMoon2ReadCropFieldSignTracker,
    HarvestMoonReadNoticeBoardTracker,
    HarvestMoon2RestaurantEntranceTracker,
    HarvestMoon2BuyLunchSetTracker,
    HarvestMoon2BuyBeverageSetTracker,
    HarvestMoon2BuyTodaysSpecialTracker,
    HarvestMoon2WriteDiaryAndSleepTracker,
    HarvestMoon2EquipSickleTracker,
    HarvestMoon2EquipHammerTracker,
    HarvestMoon2EquipFishingRodTracker,
    HarvestMoon2EquipNetReplacingAxTracker,
    HarvestMoon2EquipRosemarySeedsReplacingAxTracker,
    HarvestMoon2EquipSickleReplacingSprinklerTracker,
    HarvestMoon2EquipNetReplacingHoeTracker,
    HarvestMoon1ShipEggTracker,
    # HarvestMoon1RestoreFenceTracker,
    HarvestMoon1HarvestCenterTurnipTracker,
    HarvestMoon1WaterCenterTurnipTracker,
    # HarvestMoon2ShipEggplantTracker,
    HarvestMoon2Cross500mLineTracker,
    HarvestMoon2Cross1000mLineTracker,
    HarvestMoon2HarvestCenterEggplantTracker,
    HarvestMoon2HarvestCenterCarrotTracker,
    HarvestMoon2WaterCenterPotatoTracker,
    HarvestMoon2WaterCenterAsparagusTracker,
    HarvestMoon2ReadComputersArticleTracker,
    HarvestMoon2ReadBouldersArticleTracker,
    HarvestMoon2ReadCropsArticleTracker,
)

GAME_TO_GB_NAME = {
    "harvest_moon_1": "HarvestMoon1.gbc",
    "harvest_moon_2": "HarvestMoon2.gbc",
    "harvest_moon_3": "HarvestMoon3.gbc",
}
""" Expected save name for each game. Save the file to <storage_dir_from_config_file>/<game_name>_rom_data/<gb_name>"""

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "harvest_moon_1": HarvestMoon1Parser,
    "harvest_moon_2": HarvestMoon2Parser,
    "harvest_moon_3": HarvestMoon3Parser,
}
""" Mapping of game names to their corresponding strongest StateParser classes. 
Unless you have a very good reason, you should always use the STRONGEST possible parser for a given game. 
The parser itself does not affect performance, as for it to perform a read / screen comparison operation , it must be called upon by the state tracker.
This means there is never a reason to use a weaker parser. 
"""


AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "harvest_moon_1": {
        "default": HarvestMoonOCRTracker,
        "cow_barn_test": HarvestMoonCowBarnTracker,
        "chicken_coop_test": HarvestMoonChickenCoopTracker,
        "storage_shed_test": HarvestMoonStorageTracker,
        "pickup_watercan_test": HarvestMoonPickupWaterCanTracker,
        "go_to_sleep_test": HarvestMoonGoToSleepTracker,
        "feed_spirit_test": HarvestMoonFeedSpiritTracker,
        "help_spirit_earthquake_test": HarvestMoonHelpSpiritEarthquakeTracker,
        "water_turnip_test": HarvestMoonWaterTurnipTracker,
        "buy_material_test": HarvestMoonBuyMaterialTracker,
        "buy_chicken_test": HarvestMoonBuyChickenTracker,
        "buy_cow_brush_test": HarvestMoonBuyCowBrushTracker,
        "buy_saddlebag_test": HarvestMoonBuySaddlebagTracker,
        "buy_milker_test": HarvestMoonBuyMilkerTracker,
        "buy_potato_seeds_test": HarvestMoonBuyPotatoSeedsTracker,
        "buy_turnip_seeds_test": HarvestMoonBuyTurnipSeedsTracker,
        "buy_rice_ball_test": HarvestMoonBuyRiceBallTracker,
        "open_storage_list_test": HarvestMoonOpenStorageListTracker,
        "find_rainy_money_test": HarvestMoonFindRainyMoneyTracker,
        "find_lost_bird_test": HarvestMoonFindLostBirdTracker,
        "speak_to_blue_hair_girl_test": HarvestMoonSpeakToBlueHairGirlTracker,
        "fill_chicken_fodder_test": HarvestMoonFillChickenFodderTracker,
        "pickup_sickle_test": HarvestMoonPickupSickleTracker,
        "pickup_hoe_test": HarvestMoonPickupHoeTracker,
        "pickup_hammer_test": HarvestMoonPickupHammerTracker,
        "pickup_grass_seed_test": HarvestMoonPickupGrassSeedTracker,
        "buy_croissant_test": HarvestMoonBuyCroissantTracker,
        "buy_cake_test": HarvestMoonBuyCakeTracker,
        "go_to_church_pray_test": HarvestMoonGoToChurchPrayTracker,
        "speak_to_golden_hair_girl_test": HarvestMoonSpeakToGoldenHairGirlTracker,
        "speak_to_pink_hair_girl_test": HarvestMoonSpeakToPinkHairGirlTracker,
        "open_menu_test": HarvestMoonOpenMenuTracker,
        "ship_egg_test": HarvestMoon1ShipEggTracker,
        # "restore_fence_test": HarvestMoon1RestoreFenceTracker,
        "harvest_center_turnip_test": HarvestMoon1HarvestCenterTurnipTracker,
        "water_center_turnip_test": HarvestMoon1WaterCenterTurnipTracker,
    },
    "harvest_moon_2": {
        "default": HarvestMoonOCRTracker,
        "cow_barn_test": HarvestMoon2CowBarnTracker,
        "chicken_coop_test": HarvestMoon2ChickenCoopTracker,
        "hospital_entrance_test": HarvestMoon2HospitalEntranceTracker,
        "animal_shop_entrance_test": HarvestMoon2AnimalShopEntranceTracker,
        "library_entrance_test": HarvestMoon2LibraryEntranceTracker,
        "tool_shop_entrance_test": HarvestMoon2ToolShopEntranceTracker,
        "carpenter_entrance_test": HarvestMoon2CarpenterEntranceTracker,
        "find_lucky_money_test": HarvestMoon2FindLuckyMoneyTracker,        
        "flower_shop_entrance_test": HarvestMoon2FlowerShopEntranceTracker,
        "buy_potato_seeds_test": HarvestMoon2BuyPotatoSeedsTracker,
        "buy_asparagus_seeds_test": HarvestMoon2BuyAsparagusSeedsTracker,
        "restaurant_entrance_test": HarvestMoon2RestaurantEntranceTracker,
        "buy_lunch_set_test": HarvestMoon2BuyLunchSetTracker,
        "buy_beverage_set_test": HarvestMoon2BuyBeverageSetTracker,
        "buy_todays_special_test": HarvestMoon2BuyTodaysSpecialTracker,
        "write_diary_and_sleep_test": HarvestMoon2WriteDiaryAndSleepTracker,
        "read_secret_garden_sign_test": HarvestMoon2ReadSecretGardenSignTracker,
        "read_crop_field_sign_test": HarvestMoon2ReadCropFieldSignTracker,
        "equip_sickle_test": HarvestMoon2EquipSickleTracker,
        "equip_hammer_test": HarvestMoon2EquipHammerTracker,
        "equip_fishing_rod_test": HarvestMoon2EquipFishingRodTracker,
        "equip_net_replacing_ax_test": HarvestMoon2EquipNetReplacingAxTracker,
        "equip_rosemary_seeds_replacing_ax_test": HarvestMoon2EquipRosemarySeedsReplacingAxTracker,
        "equip_sickle_replacing_sprinkler_test": HarvestMoon2EquipSickleReplacingSprinklerTracker,
        "equip_net_replacing_hoe_test": HarvestMoon2EquipNetReplacingHoeTracker,
        # "ship_eggplant_test": HarvestMoon2ShipEggplantTracker,
        "cross_500m_line_test": HarvestMoon2Cross500mLineTracker,
        "cross_1000m_line_test": HarvestMoon2Cross1000mLineTracker,
        "harvest_center_eggplant_test": HarvestMoon2HarvestCenterEggplantTracker,
        "harvest_center_carrot_test": HarvestMoon2HarvestCenterCarrotTracker,
        "water_center_potato_test": HarvestMoon2WaterCenterPotatoTracker,
        "water_center_asparagus_test": HarvestMoon2WaterCenterAsparagusTracker,
        "read_computers_article_test": HarvestMoon2ReadComputersArticleTracker,
        "read_boulders_article_test": HarvestMoon2ReadBouldersArticleTracker,
        "read_selling_crops_article_test": HarvestMoon2ReadCropsArticleTracker,
        
        "storage_shed_test": HarvestMoonStorageTracker,
        "water_turnip_test": HarvestMoonWaterTurnipTracker,
        "open_storage_list_test": HarvestMoonOpenStorageListTracker,
        "read_village_sign_test": HarvestMoonReadVillageSignTracker,
        "read_farm_sign_test": HarvestMoonReadFarmSignTracker,
        "read_notice_board_test": HarvestMoonReadNoticeBoardTracker,
        "open_menu_test": HarvestMoonOpenMenuTracker,
    },
    "harvest_moon_3": {
        "default": HarvestMoonOCRTracker,
        "chicken_coop_test": HarvestMoon3ChickenCoopTracker,
        "read_secret_garden_sign_test": HarvestMoon3ReadSecretGardenSignTracker,
        "read_morning_market_sign_test": HarvestMoon3ReadMorningMarketSignTracker,
        "read_storage_sign_test": HarvestMoon3ReadStorageSignTracker,
        "speak_to_Kirk_village_test": HarvestMoon3SpeakToKirkVillageTracker,
        "take_ferry_back_test": HarvestMoon3TakeFerryTracker,
        "speak_to_Joe_test": HarvestMoon3SpeakToJoeTracker,
        "speak_to_Lukia_test": HarvestMoon3SpeakToLukiaTracker,
        "speak_to_Lucus_test": HarvestMoon3SpeakToLucusTracker,
        "speak_to_Lyla_test": HarvestMoon3SpeakToLylaTracker,
        "buy_meal_set_test": HarvestMoon3BuyMealSetTracker,
        "choose_coffee_to_buy_test": HarvestMoon3BuyCoffeeTracker,
        "shopping_mall_entrance_test": HarvestMoon3ShoppingMallEntranceTracker,
        "farmers_union_entrance_test": HarvestMoon3FarmersUnionEntranceTracker,
        "aquarium_entrance_test": HarvestMoon3AquariumEntranceTracker,
        "theatre_entrance_test": HarvestMoon3TheatreEntranceTracker,
        "hot_spring_entrance_test": HarvestMoon3HotSpringEntranceTracker,
        "open_menu_test": HarvestMoonOpenMenuTracker,
        "farm_entrance_test": HarvestMoon3FarmEntranceTracker,
        "village_entrance_test": HarvestMoon3VillageEntranceTracker,
        "grassland_entrance_test": HarvestMoon3GrasslandEntranceTracker, 
        "forest_entrance_test": HarvestMoon3ForestEntranceTracker,
        "cliff_entrance_test": HarvestMoon3CliffEntranceTracker,
        "mountain_entrance_test": HarvestMoon3MountainEntranceTracker,
        "read_ferry_sign_test": HarvestMoon3ReadFerrySignTracker,
        "find_secret_savings_test": HarvestMoon3FindSecretSavingsTracker,
        "choose_tea_to_buy_test": HarvestMoon3ChooseTeaTracker,
        "choose_asparagus_seeds_to_buy_test": HarvestMoon3ChooseAsparagusSeedsTracker,
        "choose_potato_seeds_to_buy_test": HarvestMoon3BuyPotatoSeedsTracker,
        "choose_turnip_seeds_to_buy_test": HarvestMoon3BuyTurnipSeedsTracker,
        "fill_cow_fodder_test": HarvestMoon3FeedCowFodderTracker,
        
    },
}
""" Mapping of game names to their available StateTracker classes with string identifiers. """


AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "harvest_moon_1": {"default": Emulator},
    "harvest_moon_2": {"default": Emulator},
    "harvest_moon_3": {"default": Emulator},
}
""" Mapping of game names to their available Emulator classes with string identifiers. """
