gameboy_wait_ticks: 8 # number of emulator ticks to wait after an action. This is in addition to the press step time. So total ticks to wait after an action is gameboy_wait_ticks + gameboy_press_step + 1.
gameboy_press_step: 5
gameboy_headed_emulation_speed: 5 # Set this to a multiplier to speed up emulation with a window, e.g. 2 for 2x speed
gameboy_max_steps: 10000
gameboy_hard_max_steps: 1000000
gameboy_random_play_max_steps: 200
gameboy_default_save_video: false
gameboy_headless_render: true # If true, will not open a window when running the emulator by default.
gameboy_reduce_video_resolution: false # If true, will reduce the resolution of saved videos to 1/2 width and 1/2 height to save space.
gameboy_dev_play_stop: false

# If true, will immediately freeze the emulator and allow the user to perform useful state specific actions. Only for development.