pokemon_red_rom_data_path: "pokemon/pokemon_red/"
pokemon_crystal_rom_data_path: "pokemon/pokemon_crystal/"
pokemon_fools_gold_rom_data_path: "pokemon/pokemon_fools_gold/"
pokemon_prism_rom_data_path: "pokemon/pokemon_prism/"
pokemon_brown_rom_data_path: "pokemon/pokemon_brown/"
pokemon_starbeasts_rom_data_path: "pokemon/pokemon_starbeasts/"
hamtaro_ham_hams_unite_rom_data_path: "hamtaro/ham_hams_unite/"
legend_of_zelda_links_awakening_rom_data_path: "legend_of_zelda/legend_of_zelda_links_awakening/"
legend_of_zelda_the_oracle_of_seasons_rom_data_path: "legend_of_zelda/legend_of_zelda_the_oracle_of_seasons/"
sword_of_hope_1_rom_data_path: "sword_of_hope/sword_of_hope_1/"
sword_of_hope_2_rom_data_path: "sword_of_hope/sword_of_hope_2/"
deja_vu_1_rom_data_path: "deja_vu/deja_vu_1/"
deja_vu_2_rom_data_path: "deja_vu/deja_vu_2/"
runes_of_virtue_1_rom_data_path: "runes_of_virtue/runes_of_virtue_1/"
runes_of_virtue_2_rom_data_path: "runes_of_virtue/runes_of_virtue_2/"
harry_potter_philosophers_stone_rom_data_path: "harry_potter/harry_potter_philosophers_stone/"
harry_potter_chamber_of_secrets_rom_data_path: "harry_potter/harry_potter_chamber_of_secrets/"
harvest_moon_1_rom_data_path: "harvest_moon/harvest_moon_1/"
harvest_moon_2_rom_data_path: "harvest_moon/harvest_moon_2/"
harvest_moon_3_rom_data_path: "harvest_moon/harvest_moon_3/"
bomberman_pocket_rom_data_path: "bomberman/bomberman_pocket/"
bomberman_quest_rom_data_path: "bomberman/bomberman_quest/"
bomberman_max_rom_data_path: "bomberman/bomberman_max/"

survival_kids_1_rom_data_path: "survival_kids/survival_kids_1/"
survival_kids_2_rom_data_path: "survival_kids/survival_kids_2/"