from typing import Optional, Union, Type, Dict
from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator
from gameboy_worlds.emulation.deja_vu.emulators import DejaVuEmulator
from gameboy_worlds.emulation.deja_vu.parsers import DejaVu1StateParser, DejaVu2StateParser
# deja_vu_1 trackers
from gameboy_worlds.emulation.deja_vu.trackers import (
    DejaVu1CheckGunTestTracker,
    DejaVu1CheckNote2TestTracker,
    DejaVu1CheckMapTestTracker,
    DejaVu1CheckPhotoTestTracker,
    DejaVu1CheckSnapshotTestTracker,
    DejaVu1CloseDoorTestTracker,
    DejaVu1CloseElevatorDoorTestTracker,
    DejaVu1ClosePocketTestTracker,
    DejaVu1CloseWalletTestTracker,
    DejaVu1CoatTestTracker,
    DejaVu1EnterCellarTestTracker,
    DejaVu1EnterConnectingRoomTestTracker,
    DejaVu1EnterElevatorTestTracker,
    DejaVu1EnterEmptyRoomFromMapTestTracker,
    DejaVu1EnterShermanTestTracker,
    DejaVu1EnterTaxiTestTracker,
    DejaVu1EnterWestendTestTracker,
    DejaVu1GoNewsstandTestTracker,
    DejaVu1GotoApartmentTestTracker,
    DejaVu1GotoOfficeTestTracker,
    DejaVu1GotoWestendTestTracker,
    DejaVu1HitBottleTestTracker,
    DejaVu1HitMuggerTestTracker,
    DejaVu1MeetMuggerTestTracker,
    DejaVu1OpenDeskTestTracker,
    DejaVu1OpenDoorTestTracker,
    DejaVu1OpenElevatorDoorTestTracker,
    DejaVu1OpenPocketTestTracker,
    DejaVu1OpenSpigotTestTracker,
    DejaVu1OpenWalletTestTracker,
    DejaVu1PayTaxiTestTracker,
    DejaVu1ShootDoorTestTracker,
    DejaVu1TakeGunTestTracker,
    DejaVu1CheckCoatTestTracker,
    DejaVu1TalkToTaxiDriverTestTracker,
    DejaVu1UnlockCarDoorTestTracker,
    DejaVu1UnlockFrontDoorTestTracker,
    DejaVu1CloseDashbrdTestTracker,
    DejaVu1OpenDashbrdTestTracker,
    DejaVu1UnlockOfficeDoorTestTracker,
    DejaVu2ChatTaxiDriverTestTracker,
    DejaVu2EnterChicagoTaxiTestTracker,
)
# deja_vu_2 trackers
from gameboy_worlds.emulation.deja_vu.trackers import (
    DejaVu2Buy2ChipsTestTracker,
    DejaVu2CheckNewsclip1TestTracker,
    DejaVu2CloseDoorFromMapTestTracker,
    DejaVu2ClosePantsPocketTestTracker,
    DejaVu2CloseWallet1TestTracker,
    DejaVu2EnterHallwayTestTracker,
    DejaVu2OpenBathroomDoorTestTracker,
    DejaVu2OpenDoorFromMapTestTracker,
    DejaVu2OpenPantsPocketTestTracker,
    DejaVu2OpenTrenchCoatTestTracker,
    DejaVu2OpenWallet1TestTracker,
    DejaVu2PutOnPantsTestTracker,
    DejaVu2PutOnTrenchCoatTestTracker,
    DejaVu2TakeGumTestTracker,
    DejaVu2TakeLicense1TestTracker,
    DejaVu2TakeNewsclip1TestTracker,
    DejaVu2TakePantsTestTracker,
    DejaVu2ReturnToCashierTestTracker,
    DejaVu2CashOutTestTracker,
    DejaVu2ExitCasinoTestTracker,
    DejaVu2OpenLobbyDoorTestTracker,
    DejaVu2TalkInTrainStationTestTracker,
    DejaVu2VisitCounterTestTracker,
    DejaVu2CheckTimetableTestTracker,
    DejaVu2TakePamphletTestTracker,
    DejaVu2EnterPlatformTestTracker,
    DejaVu2EnterTrainTestTracker,
    DejaVu2BuyTicketTestTracker,
    DejaVu2CheckGirlTestTracker,
    DejaVu2CheckSignTestTracker,
    DejaVu2BuyNewspaperTestTracker,
    DejaVu2ChatSellerTestTracker,
    DejaVu2TakeNewsclip4TestTracker,
)
from gameboy_worlds.emulation.deja_vu.trackers import  DejaVuOCRTracker
GAME_TO_GB_NAME = {
    "deja_vu_1": "DejaVu.gbc",
    "deja_vu_2": "DejaVu.gbc",
}
""" Expected save name for each game. Save the file to <storage_dir_from_config_file>/<game_name>_rom_data/<gb_name>"""

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "deja_vu_1": DejaVu1StateParser,
    "deja_vu_2": DejaVu2StateParser,
}
""" Mapping of game names to their corresponding strongest StateParser classes. 
Unless you have a very good reason, you should always use the STRONGEST possible parser for a given game. 
The parser itself does not affect performance, as for it to perform a read / screen comparison operation , it must be called upon by the state tracker.
This means there is never a reason to use a weaker parser. 
"""


AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "deja_vu_1": {
        "default": DejaVuOCRTracker,
        "take_coat_test": DejaVu1CoatTestTracker,
        "take_gun_test": DejaVu1TakeGunTestTracker,
        "open_door_test": DejaVu1OpenDoorTestTracker,
        "close_door_test": DejaVu1CloseDoorTestTracker,
        "open_pocket_test": DejaVu1OpenPocketTestTracker,
        "open_wallet_test": DejaVu1OpenWalletTestTracker,
        "close_pocket_test": DejaVu1ClosePocketTestTracker,
        "close_wallet_test": DejaVu1CloseWalletTestTracker,
        "check_coat_test": DejaVu1CheckCoatTestTracker,
        "check_gun_test": DejaVu1CheckGunTestTracker,
        "hit_bottle_test": DejaVu1HitBottleTestTracker,
        "open_spigot_test": DejaVu1OpenSpigotTestTracker,
        "enter_cellar_test": DejaVu1EnterCellarTestTracker,
        "enter_connecting_room_test": DejaVu1EnterConnectingRoomTestTracker,
        # "make_bet_test": DejaVu1MakeBetTestTracker,
        "enter_empty_room_from_map_test": DejaVu1EnterEmptyRoomFromMapTestTracker,
        "unlock_front_door_test": DejaVu1UnlockFrontDoorTestTracker,
        "meet_mugger_test": DejaVu1MeetMuggerTestTracker,
        "hit_mugger_test": DejaVu1HitMuggerTestTracker,
        "unlock_car_door_test": DejaVu1UnlockCarDoorTestTracker,
        "open_dashbrd_test": DejaVu1OpenDashbrdTestTracker,
        "close_dashbrd_test": DejaVu1CloseDashbrdTestTracker,
        "check_note2_test": DejaVu1CheckNote2TestTracker,
        "check_map_test": DejaVu1CheckMapTestTracker,
        "check_snapshot_test": DejaVu1CheckSnapshotTestTracker,
        "go_newsstand_test": DejaVu1GoNewsstandTestTracker,
        "enter_taxi_test": DejaVu1EnterTaxiTestTracker,
        "talk_to_taxi_driver_test": DejaVu1TalkToTaxiDriverTestTracker,
        "goto_westend_test": DejaVu1GotoWestendTestTracker,
        "pay_taxi_test": DejaVu1PayTaxiTestTracker,
        "goto_apartment_test": DejaVu1GotoApartmentTestTracker,
        "enter_westend_test": DejaVu1EnterWestendTestTracker,
        "open_elevator_door_test": DejaVu1OpenElevatorDoorTestTracker,
        "enter_elevator_test": DejaVu1EnterElevatorTestTracker,
        "close_elevator_door_test": DejaVu1CloseElevatorDoorTestTracker,
        "check_photo_test": DejaVu1CheckPhotoTestTracker,
        # "shoot_door_test": DejaVu1ShootDoorTestTracker,
        # "open_desk_test": DejaVu1OpenDeskTestTracker,
        # "enter_sherman_test": DejaVu1EnterShermanTestTracker,
        # "goto_office_test": DejaVu1GotoOfficeTestTracker,
        # "unlock_office_door_test": DejaVu1UnlockOfficeDoorTestTracker,
    },
    "deja_vu_2": {
        "default": DejaVuOCRTracker,
        "open_trench_coat_pocket_test": DejaVu2OpenTrenchCoatTestTracker,
        "open_bathroom_door_test": DejaVu2OpenBathroomDoorTestTracker,
        "take_gum_test": DejaVu2TakeGumTestTracker,
        "open_pants_pocket_test": DejaVu2OpenPantsPocketTestTracker,
        "close_pants_pocket_test": DejaVu2ClosePantsPocketTestTracker,
        "take_pants_test": DejaVu2TakePantsTestTracker,
        "put_on_trench_coat_test": DejaVu2PutOnTrenchCoatTestTracker,
        "put_on_pants_test": DejaVu2PutOnPantsTestTracker,
        "open_wallet1_test": DejaVu2OpenWallet1TestTracker,
        "take_newsclip1_test": DejaVu2TakeNewsclip1TestTracker,
        "take_license1_test": DejaVu2TakeLicense1TestTracker,
        "close_wallet1_test": DejaVu2CloseWallet1TestTracker,
        # "open_cold_tap_test": DejaVu2OpenColdTapTestTracker,
        # "close_cold_tap_test": DejaVu2CloseColdTapTestTracker,
        "check_newsclip1_test": DejaVu2CheckNewsclip1TestTracker,
        # "take_ring1_test": DejaVu2TakeRing1TestTracker,
        "open_door_from_map_test": DejaVu2OpenDoorFromMapTestTracker,
        "close_door_from_map_test": DejaVu2CloseDoorFromMapTestTracker,
        "enter_hallway_test": DejaVu2EnterHallwayTestTracker,
        "buy_2_chips_test": DejaVu2Buy2ChipsTestTracker,
        "return_cashier_test": DejaVu2ReturnToCashierTestTracker,
        "cash_out_test": DejaVu2CashOutTestTracker,
        "open_lobby_door_test": DejaVu2OpenLobbyDoorTestTracker,
        "exit_casino_test": DejaVu2ExitCasinoTestTracker,
        "talk_in_train_station_test": DejaVu2TalkInTrainStationTestTracker,
        "visit_counter_test": DejaVu2VisitCounterTestTracker,
        # "take_pamphlet_test": DejaVu2TakePamphletTestTracker,
        "check_timetable_test": DejaVu2CheckTimetableTestTracker,
        "enter_platform_track6_test": DejaVu2EnterPlatformTestTracker,
        "enter_train_test": DejaVu2EnterTrainTestTracker,
        "buy_ticket_test": DejaVu2BuyTicketTestTracker,
        "check_girl_test": DejaVu2CheckGirlTestTracker,
        "check_sign_test": DejaVu2CheckSignTestTracker,
        "chat_seller_test": DejaVu2ChatSellerTestTracker,
        "buy_newspaper_test": DejaVu2BuyNewspaperTestTracker,
        "take_newsclip4_test": DejaVu2TakeNewsclip4TestTracker,
        "enter_chicago_taxi_test": DejaVu2EnterChicagoTaxiTestTracker,
        "chat_taxi_driver_test": DejaVu2ChatTaxiDriverTestTracker,
    },
}
""" Mapping of game names to their available StateTracker classes with string identifiers. """


AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "deja_vu_1": {
        "default": DejaVuEmulator,
    },
    "deja_vu_2": {
        "default": DejaVuEmulator,
    },
}
""" Mapping of game names to their available Emulator classes with string identifiers. """
