"""Emulation registry for Survival Kids games."""

from typing import Dict, Type

from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator
from gameboy_worlds.emulation.survival_kids.parsers import (
    SurvivalKids2Parser,
    SurvivalKidsParser,
)
from gameboy_worlds.emulation.survival_kids.trackers import (
    SurvivalKidsAfterFillingWaterTracker,
    SurvivalKidsAfternoonReferenceTracker,
    SurvivalKidsAnimalKilledTracker,
    SurvivalKidsBagIconTracker,
    SurvivalKidsCanteenActionMenuTracker,
    SurvivalKidsCanteenChosenTracker,
    SurvivalKidsCanteenDrinkSelectedTracker,
    SurvivalKidsCanteenPickupDialogueTracker,
    SurvivalKidsCanteenTakeLeaveMenuTracker,
    SurvivalKidsCanteenUseSelectedTracker,
    SurvivalKidsChapter1PathClearedTracker,
    SurvivalKidsDayReferenceTracker,
    SurvivalKidsDrinkWaterTracker,
    SurvivalKidsEnteredShelterTracker,
    SurvivalKidsFeatherTakeLeaveMenuTracker,
    SurvivalKidsFireLitTracker,
    SurvivalKidsFoundRiverTracker,
    SurvivalKidsGameViewportChangedTracker,
    SurvivalKidsGotTheBrdfeatherTracker,
    SurvivalKidsGotTheSharpStoneTracker,
    SurvivalKidsGotTheStickTracker,
    SurvivalKidsGotTheStoneTracker,
    SurvivalKidsGotTheTreeBarkTracker,
    SurvivalKidsGotTheVineTracker,
    SurvivalKidsGotTheWaterTracker,
    SurvivalKidsHpChangedTracker,
    SurvivalKidsHudTracker,
    SurvivalKidsHungerChangedTracker,
    SurvivalKidsInTheShelterTracker,
    SurvivalKidsInventoryOpenTracker,
    SurvivalKidsKindlingMergedTracker,
    SurvivalKidsKnifeChosenTracker,
    SurvivalKidsKnifeEquippedScreenTracker,
    SurvivalKidsKnifeEquippedTracker,
    SurvivalKidsMergeConfirmTracker,
    SurvivalKidsMergeMenuTracker,
    SurvivalKidsMeatActionMenuTracker,
    SurvivalKidsMeatEatenDialogueTracker,
    SurvivalKidsMeatEatSelectedTracker,
    SurvivalKidsNewPath1FoundTracker,
    SurvivalKidsNewPath2FoundTracker,
    SurvivalKidsNightReferenceTracker,
    SurvivalKidsObjectTracker,
    SurvivalKidsOCRTracker,
    SurvivalKidsPickupItemDialogueTracker,
    SurvivalKidsPathAfterBlockingGrassTracker,
    SurvivalKidsResolveHungerTracker,
    SurvivalKidsSelectKindlingTracker,
    SurvivalKidsSelectTakeTracker,
    SurvivalKidsSharpStoneFoundTracker,
    SurvivalKidsStaminaChangedTracker,
    SurvivalKidsStatusBarChangedTracker,
    SurvivalKidsTakeLeaveMenuTracker,
    SurvivalKidsThirstChangedTracker,
    SurvivalKidsTracker,
    SurvivalKidsUseKindlingTracker,
    SurvivalKidsVitalsTracker,
    SurvivalKidsWaterMenuOpenTracker,
)


GAME_TO_GB_NAME: Dict[str, str] = {
    "survival_kids_1": "SurvivalKids.gbc",
    "survival_kids_2": "SurvivalKids2CN.gbc",
}

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "survival_kids_1": SurvivalKidsParser,
    "survival_kids_2": SurvivalKids2Parser,
}

AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "survival_kids_1": {
        "default": SurvivalKidsTracker,
        "hud": SurvivalKidsHudTracker,
        "ocr": SurvivalKidsOCRTracker,
        "vitals": SurvivalKidsVitalsTracker,
        "status_bar_changed_test": SurvivalKidsStatusBarChangedTracker,
        "hp_changed_test": SurvivalKidsHpChangedTracker,
        "hunger_changed_test": SurvivalKidsHungerChangedTracker,
        "resolve_hunger_test": SurvivalKidsResolveHungerTracker,
        "thirst_changed_test": SurvivalKidsThirstChangedTracker,
        "drink_water_test": SurvivalKidsDrinkWaterTracker,
        "stamina_changed_test": SurvivalKidsStaminaChangedTracker,
        "game_viewport_changed_test": SurvivalKidsGameViewportChangedTracker,
        "inventory_open_test": SurvivalKidsInventoryOpenTracker,
        "pickup_item_dialogue_test": SurvivalKidsPickupItemDialogueTracker,
        "canteen_pickup_dialogue_test": SurvivalKidsCanteenPickupDialogueTracker,
        "bag_icon_test": SurvivalKidsBagIconTracker,
        "object_test": SurvivalKidsObjectTracker,
        "knife_equipped_test": SurvivalKidsKnifeEquippedTracker,
        "knife_chosen_test": SurvivalKidsKnifeChosenTracker,
        "merge_menu_test": SurvivalKidsMergeMenuTracker,
        "merge_confirm_test": SurvivalKidsMergeConfirmTracker,
        "canteen_chosen_test": SurvivalKidsCanteenChosenTracker,
        "kindling_merged_test": SurvivalKidsKindlingMergedTracker,
        "take_leave_menu_test": SurvivalKidsTakeLeaveMenuTracker,
        "select_take_test": SurvivalKidsSelectTakeTracker,
        "canteen_take_leave_menu_test": SurvivalKidsCanteenTakeLeaveMenuTracker,
        "canteen_action_menu_test": SurvivalKidsCanteenActionMenuTracker,
        "canteen_drink_selected_test": SurvivalKidsCanteenDrinkSelectedTracker,
        "canteen_use_selected_test": SurvivalKidsCanteenUseSelectedTracker,
        "animal_killed_test": SurvivalKidsAnimalKilledTracker,
        "chapter1_path_cleared_test": SurvivalKidsChapter1PathClearedTracker,
        "path_after_blocking_grass_test": SurvivalKidsPathAfterBlockingGrassTracker,
        "in_the_shelter_test": SurvivalKidsInTheShelterTracker,
        "new_path_1_found_test": SurvivalKidsNewPath1FoundTracker,
        "new_path_2_found_test": SurvivalKidsNewPath2FoundTracker,
        "sharp_stone_found_test": SurvivalKidsSharpStoneFoundTracker,
        "day_reference_test": SurvivalKidsDayReferenceTracker,
        "night_reference_test": SurvivalKidsNightReferenceTracker,
        "entered_shelter_test": SurvivalKidsEnteredShelterTracker,
        "found_river_test": SurvivalKidsFoundRiverTracker,
        "water_menu_open_test": SurvivalKidsWaterMenuOpenTracker,
        "after_filling_water_test": SurvivalKidsAfterFillingWaterTracker,
        "got_the_water_test": SurvivalKidsGotTheWaterTracker,
        "got_the_stick_test": SurvivalKidsGotTheStickTracker,
        "got_the_tree_bark_test": SurvivalKidsGotTheTreeBarkTracker,
        "got_the_sharp_stone_test": SurvivalKidsGotTheSharpStoneTracker,
        "got_the_stone_test": SurvivalKidsGotTheStoneTracker,
        "got_the_vine_test": SurvivalKidsGotTheVineTracker,
        "got_the_brdfeather_test": SurvivalKidsGotTheBrdfeatherTracker,
        "select_kindling_test": SurvivalKidsSelectKindlingTracker,
        "fire_lit_test": SurvivalKidsFireLitTracker,
        "use_kindling_test": SurvivalKidsUseKindlingTracker,
        "feather_take_leave_menu_test": SurvivalKidsFeatherTakeLeaveMenuTracker,
        "meat_action_menu_test": SurvivalKidsMeatActionMenuTracker,
        "meat_eat_selected_test": SurvivalKidsMeatEatSelectedTracker,
        "meat_eaten_dialogue_test": SurvivalKidsMeatEatenDialogueTracker,
    },
    "survival_kids_2": {
        "default": SurvivalKidsTracker,
        "hud": SurvivalKidsHudTracker,
        "ocr": SurvivalKidsOCRTracker,
        "vitals": SurvivalKidsVitalsTracker,
        "status_bar_changed_test": SurvivalKidsStatusBarChangedTracker,
        "hp_changed_test": SurvivalKidsHpChangedTracker,
        "hunger_changed_test": SurvivalKidsHungerChangedTracker,
        "resolve_hunger_test": SurvivalKidsResolveHungerTracker,
        "thirst_changed_test": SurvivalKidsThirstChangedTracker,
        "drink_water_test": SurvivalKidsDrinkWaterTracker,
        "stamina_changed_test": SurvivalKidsStaminaChangedTracker,
        "game_viewport_changed_test": SurvivalKidsGameViewportChangedTracker,
        "chapter1_path_cleared_test": SurvivalKidsChapter1PathClearedTracker,
        "path_after_blocking_grass_test": SurvivalKidsPathAfterBlockingGrassTracker,
        "new_path_1_found_test": SurvivalKidsNewPath1FoundTracker,
        "new_path_2_found_test": SurvivalKidsNewPath2FoundTracker,
        "sharp_stone_found_test": SurvivalKidsSharpStoneFoundTracker,
        "inventory_open_test": SurvivalKidsInventoryOpenTracker,
        "object_test": SurvivalKidsObjectTracker,
        "knife_chosen_test": SurvivalKidsKnifeChosenTracker,
        "knife_equipped_test": SurvivalKidsKnifeEquippedScreenTracker,
        "knife_equipped_prompt_test": SurvivalKidsKnifeEquippedScreenTracker,
        "got_the_stick_test": SurvivalKidsGotTheStickTracker,
        "got_the_tree_bark_test": SurvivalKidsGotTheTreeBarkTracker,
        "got_the_sharp_stone_test": SurvivalKidsGotTheSharpStoneTracker,
        "got_the_stone_test": SurvivalKidsGotTheStoneTracker,
        "got_the_vine_test": SurvivalKidsGotTheVineTracker,
        "afternoon_reference_test": SurvivalKidsAfternoonReferenceTracker,
        "day_reference_test": SurvivalKidsDayReferenceTracker,
        "night_reference_test": SurvivalKidsNightReferenceTracker,
        "entered_shelter_test": SurvivalKidsEnteredShelterTracker,
        "found_river_test": SurvivalKidsFoundRiverTracker,
    },
}

AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "survival_kids_1": {
        "default": Emulator,
    },
    "survival_kids_2": {
        "default": Emulator,
    },
}
